name: Run Puppeteer Script

on:
  schedule:
    # ทุกวันเวลา 01:00 (เวลาไทย = UTC 18:00 ของวันก่อนหน้า)
    - cron: "0 18 * * *"
  workflow_dispatch: # เผื่อกด run เองได้จากหน้า GitHub Actions

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer Script
        run: node index.js
